name: Build

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        name: Set up nix and IOHK cache
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: mlabs
          authToken: "${{ secrets.CACHIXKEY }}"
      - name: Build all project components
        working-directory: ./mlabs
        run: nix build -L .#packages.x86_64-linux."mlabs-plutus-use-cases:test:mlabs-plutus-use-cases-tests"
      - name: Run tests
        working-directory: ./mlabs
        run: nix shell -i "github:input-output-hk/cardano-node/4f65fb9a27aa7e3a1873ab4211e412af780a3648#packages.x86_64-linux.cardano-cli" "github:input-output-hk/cardano-node/4f65fb9a27aa7e3a1873ab4211e412af780a3648#packages.x86_64-linux.cardano-node" -c ./result/bin/mlabs-plutus-use-cases-tests
